[build]
publish = "site/rendered"
command = "chmod +x build.sh;./build.sh"

[[plugins]]
package = "@netlify/plugin-lighthouse"

# [[redirects]]
# from = "/*"
# to = "/404.html"
# status = 404

# [[headers]]
# # Define which paths this specific [[headers]] block will cover.
# for = "/*"
#
# [headers.values]
# X-Frame-Options = "DENY"
# X-XSS-Protection = "1; mode=block"
# Content-Security-Policy = "frame-ancestors https://www.facebook.com"
#
# # Default build command.
# # Multi-value headers are expressed with multi-line strings.
# cache-control = '''
#   max-age=0,
#   no-cache,
#   no-store,
#   must-revalidate'''
