navbar:
  - Home: index.html
  - Posts: posts.html
  - Projects: projects.html
  - Timeline: timeline.html
  - Tags: tags.html
  - Contact: contact.html

baseURL: https://sudhir.live

siteTitle: Anirudh Sudhir

siteScripts:
  # - light.js

author: Anirudh Sudhir
